cask "font-mona-sans" do
  version "1.0.1"
  sha256 "c5e44e736b72bbbd47ae7fecfde8f0c149ba2c0a436d27a2f1ec6392ba3ecd0b"

  url "https://github.com/github/mona-sans/releases/download/v#{version}/MonaSans.zip"
  name "Mona Sans"
  homepage "https://github.com/mona-sans"

  font "Mona Sans/OTF/MonaSans-Black.otf"
  font "Mona Sans/OTF/MonaSans-BlackItalic.otf"
  font "Mona Sans/OTF/MonaSans-Bold.otf"
  font "Mona Sans/OTF/MonaSans-BoldItalic.otf"
  font "Mona Sans/OTF/MonaSans-ExtraBold.otf"
  font "Mona Sans/OTF/MonaSans-ExtraBoldItalic.otf"
  font "Mona Sans/OTF/MonaSans-ExtraLight.otf"
  font "Mona Sans/OTF/MonaSans-ExtraLightItalic.otf"
  font "Mona Sans/OTF/MonaSans-Italic.otf"
  font "Mona Sans/OTF/MonaSans-Light.otf"
  font "Mona Sans/OTF/MonaSans-LightItalic.otf"
  font "Mona Sans/OTF/MonaSans-Medium.otf"
  font "Mona Sans/OTF/MonaSans-MediumItalic.otf"
  font "Mona Sans/OTF/MonaSans-Regular.otf"
  font "Mona Sans/OTF/MonaSans-SemiBold.otf"
  font "Mona Sans/OTF/MonaSans-SemiBoldItalic.otf"
  font "Mona Sans/OTF/MonaSansCondensed-Black.otf"
  font "Mona Sans/OTF/MonaSansCondensed-BlackItalic.otf"
  font "Mona Sans/OTF/MonaSansCondensed-Bold.otf"
  font "Mona Sans/OTF/MonaSansCondensed-BoldItalic.otf"
  font "Mona Sans/OTF/MonaSansCondensed-ExtraBold.otf"
  font "Mona Sans/OTF/MonaSansCondensed-ExtraBoldItalic.otf"
  font "Mona Sans/OTF/MonaSansCondensed-ExtraLight.otf"
  font "Mona Sans/OTF/MonaSansCondensed-ExtraLightItalic.otf"
  font "Mona Sans/OTF/MonaSansCondensed-Italic.otf"
  font "Mona Sans/OTF/MonaSansCondensed-Light.otf"
  font "Mona Sans/OTF/MonaSansCondensed-LightItalic.otf"
  font "Mona Sans/OTF/MonaSansCondensed-Medium.otf"
  font "Mona Sans/OTF/MonaSansCondensed-MediumItalic.otf"
  font "Mona Sans/OTF/MonaSansCondensed-Regular.otf"
  font "Mona Sans/OTF/MonaSansCondensed-SemiBold.otf"
  font "Mona Sans/OTF/MonaSansCondensed-SemiBoldItalic.otf"
  font "Mona Sans/OTF/MonaSansExpanded-Black.otf"
  font "Mona Sans/OTF/MonaSansExpanded-BlackItalic.otf"
  font "Mona Sans/OTF/MonaSansExpanded-Bold.otf"
  font "Mona Sans/OTF/MonaSansExpanded-BoldItalic.otf"
  font "Mona Sans/OTF/MonaSansExpanded-ExtraBold.otf"
  font "Mona Sans/OTF/MonaSansExpanded-ExtraBoldItalic.otf"
  font "Mona Sans/OTF/MonaSansExpanded-ExtraLight.otf"
  font "Mona Sans/OTF/MonaSansExpanded-ExtraLightItalic.otf"
  font "Mona Sans/OTF/MonaSansExpanded-Italic.otf"
  font "Mona Sans/OTF/MonaSansExpanded-Light.otf"
  font "Mona Sans/OTF/MonaSansExpanded-LightItalic.otf"
  font "Mona Sans/OTF/MonaSansExpanded-Medium.otf"
  font "Mona Sans/OTF/MonaSansExpanded-MediumItalic.otf"
  font "Mona Sans/OTF/MonaSansExpanded-Regular.otf"
  font "Mona Sans/OTF/MonaSansExpanded-SemiBold.otf"
  font "Mona Sans/OTF/MonaSansExpanded-SemiBoldItalic.otf"

  # No zap stanza required
end
