cask "font-mona-sans" do
  version "2.0"
  sha256 "7e4ea90d0a3b7f355a6e369eeaa72f07e6510f59596910d02587f8ea7249b94c"

  url "https://github.com/github/mona-sans/releases/download/v#{version}/MonaSans.zip"
  name "Mona Sans"
  homepage "https://github.com/mona-sans"

  font "MonaSans/OTF/MonaSans-Black.otf"
  font "MonaSans/OTF/MonaSans-BlackItalic.otf"
  font "MonaSans/OTF/MonaSans-Bold.otf"
  font "MonaSans/OTF/MonaSans-BoldItalic.otf"
  font "MonaSans/OTF/MonaSans-ExtraBold.otf"
  font "MonaSans/OTF/MonaSans-ExtraBoldItalic.otf"
  font "MonaSans/OTF/MonaSans-ExtraLight.otf"
  font "MonaSans/OTF/MonaSans-ExtraLightItalic.otf"
  font "MonaSans/OTF/MonaSans-Italic.otf"
  font "MonaSans/OTF/MonaSans-Light.otf"
  font "MonaSans/OTF/MonaSans-LightItalic.otf"
  font "MonaSans/OTF/MonaSans-Medium.otf"
  font "MonaSans/OTF/MonaSans-MediumItalic.otf"
  font "MonaSans/OTF/MonaSans-Regular.otf"
  font "MonaSans/OTF/MonaSans-SemiBold.otf"
  font "MonaSans/OTF/MonaSans-SemiBoldItalic.otf"
  font "MonaSans/OTF/MonaSansCondensed-Black.otf"
  font "MonaSans/OTF/MonaSansCondensed-BlackItalic.otf"
  font "MonaSans/OTF/MonaSansCondensed-Bold.otf"
  font "MonaSans/OTF/MonaSansCondensed-BoldItalic.otf"
  font "MonaSans/OTF/MonaSansCondensed-ExtraBold.otf"
  font "MonaSans/OTF/MonaSansCondensed-ExtraBoldItalic.otf"
  font "MonaSans/OTF/MonaSansCondensed-ExtraLight.otf"
  font "MonaSans/OTF/MonaSansCondensed-ExtraLightItalic.otf"
  font "MonaSans/OTF/MonaSansCondensed-Italic.otf"
  font "MonaSans/OTF/MonaSansCondensed-Light.otf"
  font "MonaSans/OTF/MonaSansCondensed-LightItalic.otf"
  font "MonaSans/OTF/MonaSansCondensed-Medium.otf"
  font "MonaSans/OTF/MonaSansCondensed-MediumItalic.otf"
  font "MonaSans/OTF/MonaSansCondensed-Regular.otf"
  font "MonaSans/OTF/MonaSansCondensed-SemiBold.otf"
  font "MonaSans/OTF/MonaSansCondensed-SemiBoldItalic.otf"
  font "MonaSans/OTF/MonaSansExpanded-Black.otf"
  font "MonaSans/OTF/MonaSansExpanded-BlackItalic.otf"
  font "MonaSans/OTF/MonaSansExpanded-Bold.otf"
  font "MonaSans/OTF/MonaSansExpanded-BoldItalic.otf"
  font "MonaSans/OTF/MonaSansExpanded-ExtraBold.otf"
  font "MonaSans/OTF/MonaSansExpanded-ExtraBoldItalic.otf"
  font "MonaSans/OTF/MonaSansExpanded-ExtraLight.otf"
  font "MonaSans/OTF/MonaSansExpanded-ExtraLightItalic.otf"
  font "MonaSans/OTF/MonaSansExpanded-Italic.otf"
  font "MonaSans/OTF/MonaSansExpanded-Light.otf"
  font "MonaSans/OTF/MonaSansExpanded-LightItalic.otf"
  font "MonaSans/OTF/MonaSansExpanded-Medium.otf"
  font "MonaSans/OTF/MonaSansExpanded-MediumItalic.otf"
  font "MonaSans/OTF/MonaSansExpanded-Regular.otf"
  font "MonaSans/OTF/MonaSansExpanded-SemiBold.otf"
  font "MonaSans/OTF/MonaSansExpanded-SemiBoldItalic.otf"

  # No zap stanza required
end
