cask "font-meslo-lg-nerd-font" do
  version "3.3.0"
  sha256 "322d3a72da704b75cce5e52a6c3b875cbff3ca5ad01b40d0e2ad2f65be21648e"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Meslo.zip"
  name "MesloLG Nerd Font families (Meslo LG)"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  livecheck do
    url :url
    strategy :github_latest
  end

  font "MesloLGLDZNerdFont-Bold.ttf"
  font "MesloLGLDZNerdFont-BoldItalic.ttf"
  font "MesloLGLDZNerdFont-Italic.ttf"
  font "MesloLGLDZNerdFont-Regular.ttf"
  font "MesloLGLDZNerdFontMono-Bold.ttf"
  font "MesloLGLDZNerdFontMono-BoldItalic.ttf"
  font "MesloLGLDZNerdFontMono-Italic.ttf"
  font "MesloLGLDZNerdFontMono-Regular.ttf"
  font "MesloLGLDZNerdFontPropo-Bold.ttf"
  font "MesloLGLDZNerdFontPropo-BoldItalic.ttf"
  font "MesloLGLDZNerdFontPropo-Italic.ttf"
  font "MesloLGLDZNerdFontPropo-Regular.ttf"
  font "MesloLGLNerdFont-Bold.ttf"
  font "MesloLGLNerdFont-BoldItalic.ttf"
  font "MesloLGLNerdFont-Italic.ttf"
  font "MesloLGLNerdFont-Regular.ttf"
  font "MesloLGLNerdFontMono-Bold.ttf"
  font "MesloLGLNerdFontMono-BoldItalic.ttf"
  font "MesloLGLNerdFontMono-Italic.ttf"
  font "MesloLGLNerdFontMono-Regular.ttf"
  font "MesloLGLNerdFontPropo-Bold.ttf"
  font "MesloLGLNerdFontPropo-BoldItalic.ttf"
  font "MesloLGLNerdFontPropo-Italic.ttf"
  font "MesloLGLNerdFontPropo-Regular.ttf"
  font "MesloLGMDZNerdFont-Bold.ttf"
  font "MesloLGMDZNerdFont-BoldItalic.ttf"
  font "MesloLGMDZNerdFont-Italic.ttf"
  font "MesloLGMDZNerdFont-Regular.ttf"
  font "MesloLGMDZNerdFontMono-Bold.ttf"
  font "MesloLGMDZNerdFontMono-BoldItalic.ttf"
  font "MesloLGMDZNerdFontMono-Italic.ttf"
  font "MesloLGMDZNerdFontMono-Regular.ttf"
  font "MesloLGMDZNerdFontPropo-Bold.ttf"
  font "MesloLGMDZNerdFontPropo-BoldItalic.ttf"
  font "MesloLGMDZNerdFontPropo-Italic.ttf"
  font "MesloLGMDZNerdFontPropo-Regular.ttf"
  font "MesloLGMNerdFont-Bold.ttf"
  font "MesloLGMNerdFont-BoldItalic.ttf"
  font "MesloLGMNerdFont-Italic.ttf"
  font "MesloLGMNerdFont-Regular.ttf"
  font "MesloLGMNerdFontMono-Bold.ttf"
  font "MesloLGMNerdFontMono-BoldItalic.ttf"
  font "MesloLGMNerdFontMono-Italic.ttf"
  font "MesloLGMNerdFontMono-Regular.ttf"
  font "MesloLGMNerdFontPropo-Bold.ttf"
  font "MesloLGMNerdFontPropo-BoldItalic.ttf"
  font "MesloLGMNerdFontPropo-Italic.ttf"
  font "MesloLGMNerdFontPropo-Regular.ttf"
  font "MesloLGSDZNerdFont-Bold.ttf"
  font "MesloLGSDZNerdFont-BoldItalic.ttf"
  font "MesloLGSDZNerdFont-Italic.ttf"
  font "MesloLGSDZNerdFont-Regular.ttf"
  font "MesloLGSDZNerdFontMono-Bold.ttf"
  font "MesloLGSDZNerdFontMono-BoldItalic.ttf"
  font "MesloLGSDZNerdFontMono-Italic.ttf"
  font "MesloLGSDZNerdFontMono-Regular.ttf"
  font "MesloLGSDZNerdFontPropo-Bold.ttf"
  font "MesloLGSDZNerdFontPropo-BoldItalic.ttf"
  font "MesloLGSDZNerdFontPropo-Italic.ttf"
  font "MesloLGSDZNerdFontPropo-Regular.ttf"
  font "MesloLGSNerdFont-Bold.ttf"
  font "MesloLGSNerdFont-BoldItalic.ttf"
  font "MesloLGSNerdFont-Italic.ttf"
  font "MesloLGSNerdFont-Regular.ttf"
  font "MesloLGSNerdFontMono-Bold.ttf"
  font "MesloLGSNerdFontMono-BoldItalic.ttf"
  font "MesloLGSNerdFontMono-Italic.ttf"
  font "MesloLGSNerdFontMono-Regular.ttf"
  font "MesloLGSNerdFontPropo-Bold.ttf"
  font "MesloLGSNerdFontPropo-BoldItalic.ttf"
  font "MesloLGSNerdFontPropo-Italic.ttf"
  font "MesloLGSNerdFontPropo-Regular.ttf"

  # No zap stanza required
end
