version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    # The actions in triage-issues.yml are updated in the Homebrew/.github repo
    ignore:
      - dependency-name: actions/stale
      - dependency-name: dessant/lock-threads
