require: 'rubocop-cask'

AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - '**/Casks/**/*'
    - 'developer/**/*'
    - 'lib/vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - 'lib/hbc/locations.rb'
    - 'lib/hbc/macos.rb'
    - 'lib/hbc/utils.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/PredicateName:
  NameWhitelist: is_32_bit?, is_64_bit?

Style/RaiseArgs:
  EnforcedStyle: exploded

Style/StringLiterals:
  EnforcedStyle: double_quotes
