AllCops:
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/brew-cask.rb'
    - '**/invalid-header-format.rb'
    - '**/spec/*.rb'
    - '**/spec/support/*.rb'
    - '**/test/*.rb'
    - '**/test/support/*.rb'
    - 'developer/**/*'
    - 'lib/**/*'
    - 'spec/cask/**/*'
    - 'test/cask/**/*'
    - 'test/Casks/**/*'
    - 'test/plist/**/*'
    - 'test/support/shared_examples/**/*'
