require: 'rubocop-cask'

AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - '**/Casks/**/*'
    - 'developer/**/*'
    - '**/vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - 'lib/hbc/locations.rb'
    - 'lib/hbc/macos.rb'
    - 'lib/hbc/utils.rb'

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - expect
    - let
    - let!
    - subject
    - watch
    - inject
    - map
    - map!
    - collect
    - collect!
    - reject
    - reject!
    - delete_if
    - with_object
  ProceduralMethods:
    - after
    - at_exit
    - before
    - benchmark
    - bm
    - bmbm
    - capture_io
    - capture_output
    - capture_subprocess_io
    - chdir
    - context
    - create
    - each_with_object
    - fork
    - measure
    - new
    - open
    - realtime
    - shutup
    - tap
    - each
    - reverse_each
  IgnoredMethods:
    - it
    - its
    - lambda
    - proc


Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/PredicateName:
  NameWhitelist: is_32_bit?, is_64_bit?

Style/RaiseArgs:
  EnforcedStyle: exploded

Style/StringLiterals:
  EnforcedStyle: double_quotes
