inherit_from: .rubocop_todo.yml

require: rubocop-cask

AllCops:
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/brew-cask.rb'
    - 'developer/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Exclude:
    - Casks/**/*

Performance/StringReplacement:
  Exclude:
    - Casks/**/*

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ExtraSpacing:
  Exclude:
    - Casks/**/*

Style/FileName:
  Exclude:
    - Casks/**/*

Style/HashSyntax:
  EnforcedStyle: hash_rockets
