require: rubocop-cask

AllCops:
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/brew-cask.rb'
    - '**/invalid-header-format.rb'
    - '**/spec/*.rb'
    - '**/spec/support/*.rb'
    - '**/test/*.rb'
    - '**/test/support/*.rb'
    - 'developer/**/*'
    - 'lib/**/*'
    - 'spec/cask/**/*'
    - 'test/cask/**/*'
    - 'test/Casks/**/*'
    - 'test/plist/**/*'
    - 'test/support/shared_examples/**/*'

Metrics/LineLength:
  Exclude:
    - '**/Casks/**/*'

Performance/StringReplacement:
  Exclude:
    - '**/Casks/**/*'

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/Documentation:
  Exclude:
    - '**/Casks/**/*'

Style/EmptyElse:
  Exclude:
    - '**/Casks/**/*'

Style/FileName:
  Exclude:
    - '**/Casks/**/*'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IndentArray:
  EnforcedStyle: align_brackets

Style/IndentHash:
  EnforcedStyle: align_braces

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '{}'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '()'

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
