jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        export HOMEBREW_COLOR=1
        export HOMEBREW_DEVELOPER=1
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew update
        # Mirror the repo as a tap.
        mkdir -p $AGENT_HOMEDIRECTORY
        rsync --archive --compress --delete $AGENT_HOMEDIRECTORY
        cd $AGENT_HOMEDIRECTORY
        echo $AGENT_HOMEDIRECTORY
        brew cask ci
      displayName: Run brew cask-test-bot
