jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        export HOMEBREW_COLOR=1
        export HOMEBREW_DEVELOPER=1
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew update
        # Mirror the repo as a tap.
        HOMEBREW_TAP_DIR=Agent.BuildDirectory
        mkdir -p "${HOMEBREW_TAP_DIR}"
        rsync --archive --compress --delete "${HOMEBREW_TAP_DIR}"
        cd "${HOMEBREW_TAP_DIR}"
        brew cask ci
      displayName: Run brew cask-test-bot
