cask "font-ysabeau" do
  version "0.003"
  sha256 "70b0a1041c81b1e37fb80951a84616ed40668293f872f47b97fb87a88d4c1c62"

  url "https://github.com/CatharsisFonts/EauDeGaramond/releases/download/v#{version}/Ysabeau_Install_v#{version}.zip"
  name "Ysabeau"
  homepage "https://github.com/CatharsisFonts/EauDeGaramond/"

  font "Ysabeau_Install_v#{version}/Ysabeau-Black.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Bold.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-BoldItalic.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Extralight.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-ExtralightItalic.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Hairline.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-HairlineItalic.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Heavy.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Italic.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Light.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-LightItalic.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Medium.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-MediumItalic.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Regular.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Semibold.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-SemiboldItalic.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Semilight.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-SemilightItalic.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Thin.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-ThinItalic.ttf"
  font "Ysabeau_Install_v#{version}/Ysabeau-Ultrabold.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-Bold.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-BoldItalic.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-Extralight.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-ExtralightItalic.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-Hairline.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-HairlineItalic.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-Italic.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-Light.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-LightItalic.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-Medium.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-MediumItalic.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-Regular.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-Semibold.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-SemiboldItalic.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-Semilight.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-SemilightItalic.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-Thin.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauInfant-ThinItalic.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauSC-Bold.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauSC-Extralight.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauSC-Hairline.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauSC-Light.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauSC-Medium.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauSC-Regular.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauSC-Semibold.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauSC-Semilight.ttf"
  font "Ysabeau_Install_v#{version}/YsabeauSC-Thin.ttf"

  # No zap stanza required
end
