#!/bin/bash
#
# brewcask-showargs
#
# A trivial `brew cask` external command, implemented in bash.
# Displays the arguments passed to it.  Example usage:
#
#     brew cask showargs these were my args
#

set -e;                # exit on uncaught error
set +o histexpand;     # don't expand history expressions

echo "$@";

#
