class FontNotoSans < Cask
  url 'http://noto.googlecode.com/files/NotoFonts-hinted-2013-04-11.zip'
  homepage 'https://code.google.com/p/noto/'
  version '1.04'
  sha1 '5fb539468e0e689d9c60c246577432e212364e8b'
  font 'fonts/individual/hinted/NotoSans-Bold.ttf',
       'fonts/individual/hinted/NotoSans-BoldItalic.ttf',
       'fonts/individual/hinted/NotoSans-Italic.ttf',
       'fonts/individual/hinted/NotoSans-Regular.ttf',
       'fonts/individual/hinted/NotoSansArmenian-Bold.ttf',
       'fonts/individual/hinted/NotoSansArmenian-Regular.ttf',
       'fonts/individual/hinted/NotoSansDevanagari-Bold.ttf',
       'fonts/individual/hinted/NotoSansDevanagari-Regular.ttf',
       'fonts/individual/hinted/NotoSansDevanagariUI-Bold.ttf',
       'fonts/individual/hinted/NotoSansDevanagariUI-Regular.ttf',
       'fonts/individual/hinted/NotoSansEthiopic-Bold.ttf',
       'fonts/individual/hinted/NotoSansEthiopic-Regular.ttf',
       'fonts/individual/hinted/NotoSansGeorgian-Bold.ttf',
       'fonts/individual/hinted/NotoSansGeorgian-Regular.ttf',
       'fonts/individual/hinted/NotoSansHebrew-Bold.ttf',
       'fonts/individual/hinted/NotoSansHebrew-Regular.ttf',
       'fonts/individual/hinted/NotoSansKhmer-Bold.ttf',
       'fonts/individual/hinted/NotoSansKhmer-Regular.ttf',
       'fonts/individual/hinted/NotoSansKhmerUI-Bold.ttf',
       'fonts/individual/hinted/NotoSansKhmerUI-Regular.ttf',
       'fonts/individual/hinted/NotoSansLao-Bold.ttf',
       'fonts/individual/hinted/NotoSansLao-Regular.ttf',
       'fonts/individual/hinted/NotoSansLaoUI-Bold.ttf',
       'fonts/individual/hinted/NotoSansLaoUI-Regular.ttf',
       'fonts/individual/hinted/NotoSansTamil-Bold.ttf',
       'fonts/individual/hinted/NotoSansTamil-Regular.ttf',
       'fonts/individual/hinted/NotoSansTamilUI-Bold.ttf',
       'fonts/individual/hinted/NotoSansTamilUI-Regular.ttf',
       'fonts/individual/hinted/NotoSansThai-Bold.ttf',
       'fonts/individual/hinted/NotoSansThai-Regular.ttf',
       'fonts/individual/hinted/NotoSansThaiUI-Bold.ttf',
       'fonts/individual/hinted/NotoSansThaiUI-Regular.ttf',
       'fonts/individual/hinted/NotoSansUI-Bold.ttf',
       'fonts/individual/hinted/NotoSansUI-BoldItalic.ttf',
       'fonts/individual/hinted/NotoSansUI-Italic.ttf',
       'fonts/individual/hinted/NotoSansUI-Regular.ttf',
       'fonts/individual/hinted/NotoSerif-Bold.ttf',
       'fonts/individual/hinted/NotoSerif-BoldItalic.ttf',
       'fonts/individual/hinted/NotoSerif-Italic.ttf',
       'fonts/individual/hinted/NotoSerif-Regular.ttf',
       'fonts/individual/hinted/NotoSerifArmenian-Bold.ttf',
       'fonts/individual/hinted/NotoSerifArmenian-Regular.ttf',
       'fonts/individual/hinted/NotoSerifGeorgian-Bold.ttf',
       'fonts/individual/hinted/NotoSerifGeorgian-Regular.ttf',
       'fonts/individual/hinted/NotoSerifLao-Bold.ttf',
       'fonts/individual/hinted/NotoSerifLao-Regular.ttf',
       'fonts/individual/hinted/NotoSerifThai-Bold.ttf',
       'fonts/individual/hinted/NotoSerifThai-Regular.ttf'
end
