cask 'jmetrik' do
  version '4.1.1'
  sha256 'a6b7fa7870232f9bf615704c810c8046b3b5ebc02ec3a920fb96e0f255b61321'

  url "https://itemanalysis.com/jmetrik/v#{version.dots_to_underscores}/jmetrik_macos_#{version.dots_to_underscores}_java7.dmg"
  name 'jMetrik'
  homepage 'http://itemanalysis.com/'

  # Installer runs install4j from the distribution in quiet mode.
  #
  # The defaults below chose the options to:
  #   accept the license agreement
  #   install to /Applications
  #   don't create a desktop icon
  #   don't launch jMetrik after installing.
  #
  # For future Cask maintainers, if any of these variables change in future
  # versions, you can run the installer manually and then check the values
  # in the following file generated by the installation:
  #   /Applications/jmetrik/.install4j/response.varfile
  #
  # Refer to the install4j command line options for additional information
  #   https://resources.ej-technologies.com/install4j/help/doc/index.html
  #
  installer script: {
                      executable: 'jMetrik Installer.app/Contents/MacOS/JavaApplicationStub',
                      args:       [
                                    '-q',
                                    '-VcreateDesktopLinkAction$Boolean=false',
                                    '-VexecutionLauncherAction$Boolean=false',
                                    '-Vsys.adminRights$Boolean=true',
                                    '-Vsys.installationDir=/Applications/jMetrik',
                                    '-Vsys.languageId=en',
                                    '-Vsys.programGroupDisabled$Boolean=true',
                                  ],
                      sudo:       true,
                    }

  uninstall script: {
                      executable: '/Applications/jMetrik/jMetrik Uninstaller.app/Contents/MacOS/JavaApplicationStub',
                      args:       [
                                    '-q',
                                    '-Vsys.adminRights$Boolean=true',
                                  ],
                      sudo:       true,
                    }

  caveats do
    depends_on_java '7+'
  end
end
