cask "llvm-arm-embedded" do
  version "16.0.0"
  sha256 "ad743e1a217f52c7d588be29ea0835d0a98a92c462bb9488c51fb566be0a3a1e"

  url "https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/releases/download/release-#{version}/LLVMEmbeddedToolchainForArm-#{version}-Darwin.tar.gz"
  name "llvm-arm-embedded"
  desc "Prebuilt LLVM toolchain for Arm embedded targets"
  homepage "https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm"

  suite "LLVMEmbeddedToolchainForArm-#{version}-Darwin"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang", target: "arm-embedded-clang"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang-16", target: "arm-embedded-clang-16"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang-cl", target: "arm-embedded-clang-cl"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang-cpp", target: "arm-embedded-clang-cpp"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang-format", target: "arm-embedded-clang-format"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang++", target: "arm-embedded-clang++"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/dsymutil", target: "arm-embedded-dsymutil"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/git-clang-format", target: "arm-embedded-git-clang-format"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/ld.lld", target: "arm-embedded-ld.lld"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/ld64.lld", target: "arm-embedded-ld64.lld"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/lld", target: "arm-embedded-lld"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/lld-link", target: "arm-embedded-lld-link"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-ar", target: "arm-embedded-llvm-ar"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-config", target: "arm-embedded-llvm-config"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-cov", target: "arm-embedded-llvm-cov"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-cxxfilt", target: "arm-embedded-llvm-cxxfilt"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-dwarfdump", target: "arm-embedded-llvm-dwarfdump"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-nm", target: "arm-embedded-llvm-nm"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-objcopy", target: "arm-embedded-llvm-objcopy"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-objdump", target: "arm-embedded-llvm-objdump"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-profdata", target: "arm-embedded-llvm-profdata"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-ranlib", target: "arm-embedded-llvm-ranlib"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-readelf", target: "arm-embedded-llvm-readelf"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-readobj", target: "arm-embedded-llvm-readobj"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-size", target: "arm-embedded-llvm-size"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-strip", target: "arm-embedded-llvm-strip"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-symbolizer", target: "arm-embedded-llvm-symbolizer"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/wasm-ld", target: "arm-embedded-wasm-ld"

  # No zap stanza required
end
