cask "llvm-arm-embedded" do
  version "16.0.0"
  sha256 "ad743e1a217f52c7d588be29ea0835d0a98a92c462bb9488c51fb566be0a3a1e"

  url "https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/releases/download/release-#{version}/LLVMEmbeddedToolchainForArm-#{version}-Darwin.tar.gz"
  name "llvm-arm-embedded"
  desc "Prebuilt LLVM toolchain for Arm embedded targets"
  homepage "https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm"

  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang++"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang-16"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang-cl"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang-cpp"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/clang-format"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/dsymutil"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/git-clang-format"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/ld.lld"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/ld64.lld"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/lld"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/lld-link"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-ar"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-config"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-cov"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-cxxfilt"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-dwarfdump"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-nm"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-objcopy"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-objdump"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-profdata"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-ranlib"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-readelf"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-readobj"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-size"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-strip"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/llvm-symbolizer"
  binary "LLVMEmbeddedToolchainForArm-#{version}-Darwin/bin/wasm-ld"

  # No zap stanza required
end
