cask :v1 => 'packer' do
  version '0.7.2'
  sha256 'bed7ddc255b5b71b139de5e30d4221926cd314a87baf0b937ba7a97c196b1286'

  url "https://dl.bintray.com/mitchellh/packer/packer_#{version}_darwin_amd64.zip"
  homepage 'http://www.packer.io/'
  license :unknown    # todo: improve this machine-generated value

  binary 'packer'
  binary 'packer-builder-amazon-chroot'
  binary 'packer-builder-amazon-ebs'
  binary 'packer-builder-amazon-instance'
  binary 'packer-builder-digitalocean'
  binary 'packer-builder-docker'
  binary 'packer-builder-googlecompute'
  binary 'packer-builder-null'
  binary 'packer-builder-openstack'
  binary 'packer-builder-parallels-iso'
  binary 'packer-builder-parallels-pvm'
  binary 'packer-builder-qemu'
  binary 'packer-builder-virtualbox-iso'
  binary 'packer-builder-virtualbox-ovf'
  binary 'packer-builder-vmware-iso'
  binary 'packer-builder-vmware-vmx'
  binary 'packer-command-build'
  binary 'packer-command-fix'
  binary 'packer-command-inspect'
  binary 'packer-command-validate'
  binary 'packer-post-processor-compress'
  binary 'packer-post-processor-docker-import'
  binary 'packer-post-processor-docker-push'
  binary 'packer-post-processor-docker-save'
  binary 'packer-post-processor-docker-tag'
  binary 'packer-post-processor-vagrant'
  binary 'packer-post-processor-vagrant-cloud'
  binary 'packer-post-processor-vsphere'
  binary 'packer-provisioner-ansible-local'
  binary 'packer-provisioner-chef-client'
  binary 'packer-provisioner-chef-solo'
  binary 'packer-provisioner-file'
  binary 'packer-provisioner-puppet-masterless'
  binary 'packer-provisioner-puppet-server'
  binary 'packer-provisioner-salt-masterless'
  binary 'packer-provisioner-shell'
end
