# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions
# Do not edit this file manually

cask "timetracker" do
  version "0.2.3"
  sha256 "90b6855024540a93a34b10d5dbbe9e956789ef47b8e632be1c0ad66c1a302564"

  url "https://github.com/bthos/time-tracker-app/releases/download/v0.2.3/TimeTracker_0.2.2_aarch64.dmg"
  name "TimeTracker"
  desc "Desktop application for automatic time tracking that shows where your working time goes, with smart handling of idle time."
  homepage "https://github.com/bthos/time-tracker-app"

  livecheck do
    url "https://github.com/bthos/time-tracker-app"
    strategy :github_latest
  end

  app "TimeTracker.app"

  zap trash: [
    "~/Library/Application Support/TimeTracker",
    "~/Library/Preferences/com.timetracker.app.plist",
  ]
end
