cask "soapui" do
  arch arm: "arm64", intel: "x64"

  version "5.10.0"
  sha256 arm:   "1b9cd5c8be2780e36343a6ed6aee443fa320d2fc19be7271ce13b782be01a099",
         intel: "825b20a857960d0a5668368626896da3388ba1a5b8d3c00927ac2df6fbe9b0d4"

  url "https://dl.eviware.com/soapuios/#{version}/SoapUI-#{arch}-#{version}.dmg",
      verified: "dl.eviware.com/soapuios/"
  name "SmartBear SoapUI"
  desc "API testing tool"
  homepage "https://www.soapui.org/"

  livecheck do
    url "https://www.soapui.org/downloads/latest-release/"
    regex(%r{href=.*?/SoapUI[._-]#{arch}[._-]v?(\d+(?:\.\d+)+)\.dmg}i)
  end

  depends_on :macos

  installer script: {
    executable: "SoapUI #{version} Installer.app/Contents/MacOS/JavaApplicationStub",
    # For future Cask maintainers, if any of these variables
    # change in future versions from SmartBear, you can run
    # the installer manually and then check the values in
    # the following file generated by the installation:
    #  /Applications/SoapUI-${version}.app/Contents/java/app/.install4j/response.varfile
    args:       [
      "-q", # Unattended mode
      "-VcreateDesktopLinkAction$Boolean=false", # Do not create a desktop icon
      "-Vsys.component.132$Boolean=true", # Install SoapUI
      "-Vsys.component.714$Boolean=false", # Do not install source
      "-Vsys.component.1263$Boolean=false", # Do not install HermesJMS
      "-Vsys.component.2393$Boolean=false", # Do not install tutorials
      "-VshowFileAction$Boolean=false", # Do not show release notes
      "-Vsys.installationDir=#{appdir}", # Install to #{appdir} (default: /Applications)
      "-VexecutionLauncherAction$Boolean=false", # Do not launch SoapUI after installing
    ],
  }

  uninstall trash: "#{appdir}/SoapUI-#{version}.app"

  zap trash: [
    "~/.soapuios",
    "~/default-soapui-workspace.xml",
    "~/Library/Application Support/SoapUI-*",
    "~/soapui-settings.xml",
  ]
end
