name: Reproducible Bug Report
description: If you’re sure it’s reproducible and not just your machine, submit an issue so we can investigate
body:
  - type: checkboxes
    attributes:
      description: Please verify that you’ve followed these steps
      options:
        - label: I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
          required: true
        - label: I have retried my command with `--force`.
          required: false
        - label: I ran `brew update-reset && brew update` and retried my command.
          required: false
        - label: I ran `brew doctor`, fixed as many issues as possible and retried my command.
          required: false
        - label: I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
          required: true
        - label: I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
          required: true
  - type: textarea
    attributes:
      label: Description of issue
    validations:
      required: true
  - type: input
    attributes:
      label: Command that failed
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output of command with `--verbose --debug`
      value: |
        <details><summary>Click to expand</summary><pre><code>

        REPLACE THIS TEXT WITH THE OUTPUT

        </code></pre></details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output of `brew doctor --verbose`
      value: |
        <details><summary>Click to expand</summary><pre><code>

        REPLACE THIS TEXT WITH THE OUTPUT

        </code></pre></details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output of `brew tap`
      value: |
        <details><summary>Click to expand</summary><pre><code>

        REPLACE THIS TEXT WITH THE OUTPUT

        </code></pre></details>
    validations:
      required: true
