name: Feature Request
description: Suggest a feature for the Cask part of Homebrew
issue_body: false
body:
  - type: textarea
    attributes:
      label: Provide a detailed description of the proposed feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the motivation for the feature?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Example use case
    validations:
      required: true
