name: Cask Request
description: For requesting new casks
issue_body: false
body:
    - type: markdown
      attributes:
        value: At the moment we don’t take cask requests. If you want a cask added, submit a [pull request](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask).
