cask "font-zed-sans" do
  version "1.2.0"
  sha256 "eb861c35c6f1639a674793f71135b1370ffefc9bd6e69a5ff5fffa2659f150c1"

  url "https://github.com/zed-industries/zed-fonts/releases/download/#{version}/zed-sans-#{version}.zip"
  name "Zed Sans"
  homepage "https://github.com/zed-industries/zed-fonts"

  font "zed-sans-bold.ttf"
  font "zed-sans-bolditalic.ttf"
  font "zed-sans-boldoblique.ttf"
  font "zed-sans-extended.ttf"
  font "zed-sans-extendedbold.ttf"
  font "zed-sans-extendedbolditalic.ttf"
  font "zed-sans-extendedboldoblique.ttf"
  font "zed-sans-extendedextrabold.ttf"
  font "zed-sans-extendedextrabolditalic.ttf"
  font "zed-sans-extendedextraboldoblique.ttf"
  font "zed-sans-extendedextralight.ttf"
  font "zed-sans-extendedextralightitalic.ttf"
  font "zed-sans-extendedextralightoblique.ttf"
  font "zed-sans-extendedheavy.ttf"
  font "zed-sans-extendedheavyitalic.ttf"
  font "zed-sans-extendedheavyoblique.ttf"
  font "zed-sans-extendeditalic.ttf"
  font "zed-sans-extendedlight.ttf"
  font "zed-sans-extendedlightitalic.ttf"
  font "zed-sans-extendedlightoblique.ttf"
  font "zed-sans-extendedmedium.ttf"
  font "zed-sans-extendedmediumitalic.ttf"
  font "zed-sans-extendedmediumoblique.ttf"
  font "zed-sans-extendedoblique.ttf"
  font "zed-sans-extendedsemibold.ttf"
  font "zed-sans-extendedsemibolditalic.ttf"
  font "zed-sans-extendedsemiboldoblique.ttf"
  font "zed-sans-extendedthin.ttf"
  font "zed-sans-extendedthinitalic.ttf"
  font "zed-sans-extendedthinoblique.ttf"
  font "zed-sans-extrabold.ttf"
  font "zed-sans-extrabolditalic.ttf"
  font "zed-sans-extraboldoblique.ttf"
  font "zed-sans-extralight.ttf"
  font "zed-sans-extralightitalic.ttf"
  font "zed-sans-extralightoblique.ttf"
  font "zed-sans-heavy.ttf"
  font "zed-sans-heavyitalic.ttf"
  font "zed-sans-heavyoblique.ttf"
  font "zed-sans-italic.ttf"
  font "zed-sans-light.ttf"
  font "zed-sans-lightitalic.ttf"
  font "zed-sans-lightoblique.ttf"
  font "zed-sans-medium.ttf"
  font "zed-sans-mediumitalic.ttf"
  font "zed-sans-mediumoblique.ttf"
  font "zed-sans-oblique.ttf"
  font "zed-sans-regular.ttf"
  font "zed-sans-semibold.ttf"
  font "zed-sans-semibolditalic.ttf"
  font "zed-sans-semiboldoblique.ttf"
  font "zed-sans-thin.ttf"
  font "zed-sans-thinitalic.ttf"
  font "zed-sans-thinoblique.ttf"

  # No zap stanza required
end
