cask "font-plemol-jp-hs" do
  version "1.7.1"
  sha256 "2d88d578f6ea814ec5f5806219f5589cb7daa3608daef255ad8a54ae8f106583"

  url "https://github.com/yuru7/PlemolJP/releases/download/v#{version}/PlemolJP_HS_v#{version}.zip"
  name "PlemolJP HS"
  homepage "https://github.com/yuru7/PlemolJP"

  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-Bold.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-BoldItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-ExtraLight.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-ExtraLightItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-Italic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-Light.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-LightItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-Medium.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-MediumItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-Regular.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-SemiBold.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-SemiBoldItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-Text.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-TextItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-Thin.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP_HS/PlemolJPHS-ThinItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-Bold.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-BoldItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-ExtraLight.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-ExtraLightItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-Italic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-Light.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-LightItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-Medium.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-MediumItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-Regular.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-SemiBold.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-SemiBoldItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-Text.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-TextItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-Thin.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJPConsole_HS/PlemolJPConsoleHS-ThinItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-Bold.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-BoldItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-ExtraLight.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-ExtraLightItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-Italic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-Light.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-LightItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-Medium.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-MediumItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-Regular.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-SemiBold.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-SemiBoldItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-Text.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-TextItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-Thin.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35_HS/PlemolJP35HS-ThinItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Bold.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-BoldItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-ExtraLight.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-ExtraLightItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Italic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Light.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-LightItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Medium.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-MediumItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Regular.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-SemiBold.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-SemiBoldItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Text.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-TextItalic.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Thin.ttf"
  font "PlemolJP_HS_v#{version}/PlemolJP35Console_HS/PlemolJP35ConsoleHS-ThinItalic.ttf"

  # No zap stanza required
end
