# Auto-generated by scripts/release.sh from homebrew/dimswitch.rb.template.
# Edit the template, not this file. The static fields (desc, zap paths,
# macOS minimum) live in the template; version / sha256 are filled in per
# release. The download URL uses `#{version}` interpolation so it tracks
# the cask version automatically.
#
# Note: cask is named "dimswitch" (marketing name) but the .app bundle and
# bundle ID still use "Dimmer" — those are baked into the signed/notarized
# binary and the persisted UserDefaults domain.
#
# Stanza order matters for `brew style` — it enforces a specific layout
# (name → desc → homepage → livecheck → depends_on → app → zap). Don't
# reorder without re-running `brew style --cask dist/dimswitch.rb`.

cask "dimswitch" do
  version "1.1.0"
  sha256 "ec09bbca90c73d7731500f3303db6a0d00cb1592c67c756a6825b238b4c00aa4"

  # `#{version}` interpolation keeps the URL self-updating per release —
  # required by `brew audit` ("Use sha256 :no_check when URL is unversioned"
  # otherwise). `verified:` declares the prefix we trust on the CDN, which
  # `brew audit` requires when the download domain differs from `homepage`.
  url "https://frn-dist.sfo3.digitaloceanspaces.com/dimmer/#{version}/Dimmer-#{version}.dmg",
      verified: "frn-dist.sfo3.digitaloceanspaces.com/dimmer/"
  name "Dimswitch"
  desc "Attention-driven brightness control for external displays via DDC/CI"
  # Source repo (johnathan-greenaway/vibrance) is private, so we point at
  # the public landing site instead — github.com/.../vibrance would 404 for
  # anyone running `brew info`. Trailing slash is required by `brew style`.
  homepage "https://dimswitch.frnds.store/"

  # `brew livecheck` auto-detects new releases by reading the same
  # version.json the in-app updater + landing site consume. Without this,
  # `brew audit --new` errors with "Version 'x.y.z' differs from '' retrieved
  # by livecheck."
  livecheck do
    url "https://frn-dist.sfo3.digitaloceanspaces.com/dimmer/latest/version.json"
    strategy :json do |json|
      json["version"]
    end
  end

  # Minimum macOS — keep in sync with LSMinimumSystemVersion in Info.plist
  # and the deployment target in Package.swift. Use the symbol form
  # (`:sonoma`) not the string-with-comparator form ("`>= :sonoma`") —
  # `brew style` enforces the symbol form for the minimum-version case.
  depends_on macos: :sonoma

  app "Dimmer.app"

  # zap removes everything the app writes outside its bundle. Per Homebrew
  # Cask convention, uninstall just removes the .app; zap is invoked via
  # `brew uninstall --zap dimswitch` for a clean wipe. Array must be
  # alphabetically sorted (Cask/ArrayAlphabetization).
  zap trash: [
    "~/Library/Application Support/Dimmer",
    "~/Library/Caches/com.dimmerapp.Dimmer",
    "~/Library/HTTPStorages/com.dimmerapp.Dimmer",
    "~/Library/Preferences/com.dimmerapp.Dimmer.plist",
    "~/Library/Saved Application State/com.dimmerapp.Dimmer.savedState",
  ]
end
