cask "font-coelacanth" do
  version "0.2.0,497a6cbf2c514f75bd3ed02d831fbb78"
  sha256 "8ece70a1abca27debaa6a2b765f3cec5f9102625018de1e1cbb4db398a0f10e7"

  url "https://gitlab.com/-/project/58955984/uploads/#{version.csv.second}/coelacanth_v#{version.csv.first}.zip"
  name "Coelacanth"
  homepage "https://gitlab.com/Fuzzypeg/coelacanth"

  livecheck do
    url "https://gitlab.com/api/v4/projects/58955984/releases"
    regex(%r{/uploads/(\h+)/coelacanth[._-]v?(\d+(?:\.\d+)+)\.zip}i)
    strategy :json do |json, regex|
      json.filter_map do |item|
        match = item["description"]&.match(regex)
        next unless match

        "#{match[2]},#{match[1]}"
      end
    end
  end

  font "Coelacanth-Bold.otf"
  font "Coelacanth-BoldIt.otf"
  font "Coelacanth-ExtraLt.otf"
  font "Coelacanth-ExtraLtIt.otf"
  font "Coelacanth-Heavy.otf"
  font "Coelacanth-HeavyIt.otf"
  font "Coelacanth-It.otf"
  font "Coelacanth-Lt.otf"
  font "Coelacanth-LtIt.otf"
  font "Coelacanth-Semibd.otf"
  font "Coelacanth-SemibdIt.otf"
  font "Coelacanth.otf"
  font "CoelacanthCaption-Bold.otf"
  font "CoelacanthCaption-BoldIt.otf"
  font "CoelacanthCaption-ExtraLt.otf"
  font "CoelacanthCaption-ExtraLtIt.otf"
  font "CoelacanthCaption-Heavy.otf"
  font "CoelacanthCaption-HeavyIt.otf"
  font "CoelacanthCaption-It.otf"
  font "CoelacanthCaption-Lt.otf"
  font "CoelacanthCaption-LtIt.otf"
  font "CoelacanthCaption-Semibd.otf"
  font "CoelacanthCaption-SemibdIt.otf"
  font "CoelacanthCaption.otf"
  font "CoelacanthDisplay-Bold.otf"
  font "CoelacanthDisplay-BoldIt.otf"
  font "CoelacanthDisplay-ExtraLt.otf"
  font "CoelacanthDisplay-ExtraLtIt.otf"
  font "CoelacanthDisplay-Heavy.otf"
  font "CoelacanthDisplay-HeavyIt.otf"
  font "CoelacanthDisplay-It.otf"
  font "CoelacanthDisplay-Lt.otf"
  font "CoelacanthDisplay-LtIt.otf"
  font "CoelacanthDisplay-Semibd.otf"
  font "CoelacanthDisplay-SemibdIt.otf"
  font "CoelacanthDisplay.otf"
  font "CoelacanthPearl-Bold.otf"
  font "CoelacanthPearl-BoldIt.otf"
  font "CoelacanthPearl-ExtraLt.otf"
  font "CoelacanthPearl-ExtraLtIt.otf"
  font "CoelacanthPearl-Heavy.otf"
  font "CoelacanthPearl-HeavyIt.otf"
  font "CoelacanthPearl-It.otf"
  font "CoelacanthPearl-Lt.otf"
  font "CoelacanthPearl-LtIt.otf"
  font "CoelacanthPearl-Semibd.otf"
  font "CoelacanthPearl-SemibdIt.otf"
  font "CoelacanthPearl.otf"
  font "CoelacanthSubcapt-Bold.otf"
  font "CoelacanthSubcapt-BoldIt.otf"
  font "CoelacanthSubcapt-ExtraLt.otf"
  font "CoelacanthSubcapt-ExtraLtIt.otf"
  font "CoelacanthSubcapt-Heavy.otf"
  font "CoelacanthSubcapt-HeavyIt.otf"
  font "CoelacanthSubcapt-It.otf"
  font "CoelacanthSubcapt-Lt.otf"
  font "CoelacanthSubcapt-LtIt.otf"
  font "CoelacanthSubcapt-Semibd.otf"
  font "CoelacanthSubcapt-SemibdIt.otf"
  font "CoelacanthSubcapt.otf"
  font "CoelacanthSubhd-Bold.otf"
  font "CoelacanthSubhd-BoldIt.otf"
  font "CoelacanthSubhd-ExtraLt.otf"
  font "CoelacanthSubhd-ExtraLtIt.otf"
  font "CoelacanthSubhd-Heavy.otf"
  font "CoelacanthSubhd-HeavyIt.otf"
  font "CoelacanthSubhd-It.otf"
  font "CoelacanthSubhd-Lt.otf"
  font "CoelacanthSubhd-LtIt.otf"
  font "CoelacanthSubhd-Semibd.otf"
  font "CoelacanthSubhd-SemibdIt.otf"
  font "CoelacanthSubhd.otf"

  # No zap stanza required
end
