cask "font-cormorant" do
  version "4.002"
  sha256 "09358a2f1f5ebefa2f54ee2e4cbda0c7b141cbe61918865c6cfb971d3e040747"

  url "https://github.com/CatharsisFonts/Cormorant/releases/download/v#{version}/Cormorant_Install_v#{version}.zip"
  name "Cormorant"
  homepage "https://github.com/CatharsisFonts/Cormorant/"

  font "Cormorant_Install_v#{version}/Cormorant-Bold.otf"
  font "Cormorant_Install_v#{version}/Cormorant-BoldItalic.otf"
  font "Cormorant_Install_v#{version}/Cormorant-Italic.otf"
  font "Cormorant_Install_v#{version}/Cormorant-Light.otf"
  font "Cormorant_Install_v#{version}/Cormorant-LightItalic.otf"
  font "Cormorant_Install_v#{version}/Cormorant-Medium.otf"
  font "Cormorant_Install_v#{version}/Cormorant-MediumItalic.otf"
  font "Cormorant_Install_v#{version}/Cormorant-Regular.otf"
  font "Cormorant_Install_v#{version}/Cormorant-SemiBold.otf"
  font "Cormorant_Install_v#{version}/Cormorant-SemiBoldItalic.otf"
  font "Cormorant_Install_v#{version}/CormorantGaramond-Bold.otf"
  font "Cormorant_Install_v#{version}/CormorantGaramond-BoldItalic.otf"
  font "Cormorant_Install_v#{version}/CormorantGaramond-Italic.otf"
  font "Cormorant_Install_v#{version}/CormorantGaramond-Light.otf"
  font "Cormorant_Install_v#{version}/CormorantGaramond-LightItalic.otf"
  font "Cormorant_Install_v#{version}/CormorantGaramond-Medium.otf"
  font "Cormorant_Install_v#{version}/CormorantGaramond-MediumItalic.otf"
  font "Cormorant_Install_v#{version}/CormorantGaramond-Regular.otf"
  font "Cormorant_Install_v#{version}/CormorantGaramond-SemiBold.otf"
  font "Cormorant_Install_v#{version}/CormorantGaramond-SemiBoldItalic.otf"
  font "Cormorant_Install_v#{version}/CormorantInfant-Bold.otf"
  font "Cormorant_Install_v#{version}/CormorantInfant-BoldItalic.otf"
  font "Cormorant_Install_v#{version}/CormorantInfant-Italic.otf"
  font "Cormorant_Install_v#{version}/CormorantInfant-Light.otf"
  font "Cormorant_Install_v#{version}/CormorantInfant-LightItalic.otf"
  font "Cormorant_Install_v#{version}/CormorantInfant-Medium.otf"
  font "Cormorant_Install_v#{version}/CormorantInfant-MediumItalic.otf"
  font "Cormorant_Install_v#{version}/CormorantInfant-Regular.otf"
  font "Cormorant_Install_v#{version}/CormorantInfant-SemiBold.otf"
  font "Cormorant_Install_v#{version}/CormorantInfant-SemiBoldItalic.otf"
  font "Cormorant_Install_v#{version}/CormorantSC-Bold.otf"
  font "Cormorant_Install_v#{version}/CormorantSC-Light.otf"
  font "Cormorant_Install_v#{version}/CormorantSC-Medium.otf"
  font "Cormorant_Install_v#{version}/CormorantSC-Regular.otf"
  font "Cormorant_Install_v#{version}/CormorantSC-SemiBold.otf"
  font "Cormorant_Install_v#{version}/CormorantUnicase-Bold.otf"
  font "Cormorant_Install_v#{version}/CormorantUnicase-Light.otf"
  font "Cormorant_Install_v#{version}/CormorantUnicase-Medium.otf"
  font "Cormorant_Install_v#{version}/CormorantUnicase-Regular.otf"
  font "Cormorant_Install_v#{version}/CormorantUnicase-SemiBold.otf"
  font "Cormorant_Install_v#{version}/CormorantUpright-Bold.otf"
  font "Cormorant_Install_v#{version}/CormorantUpright-Light.otf"
  font "Cormorant_Install_v#{version}/CormorantUpright-Medium.otf"
  font "Cormorant_Install_v#{version}/CormorantUpright-Regular.otf"
  font "Cormorant_Install_v#{version}/CormorantUpright-SemiBold.otf"

  # No zap stanza required
end
