cask "font-cormorant" do
  version "3.609"
  sha256 "e394546eec6dfdfc235b667b00bbc5b4b6144110d6ed1810fc3570098a4fba7b"

  url "https://github.com/CatharsisFonts/Cormorant/releases/download/v#{version}/Cormorant_Install_v#{version}.zip"
  name "Cormorant"
  homepage "https://github.com/CatharsisFonts/Cormorant/"

  font "Cormorant_Install_v#{version}/1. TrueType Font Files/Cormorant-Bold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/Cormorant-BoldItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/Cormorant-Italic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/Cormorant-Light.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/Cormorant-LightItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/Cormorant-Medium.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/Cormorant-MediumItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/Cormorant-Regular.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/Cormorant-SemiBold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/Cormorant-SemiBoldItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantGaramond-Bold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantGaramond-BoldItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantGaramond-Italic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantGaramond-Light.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantGaramond-LightItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantGaramond-Medium.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantGaramond-MediumItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantGaramond-Regular.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantGaramond-SemiBold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantGaramond-SemiBoldItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantInfant-Bold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantInfant-BoldItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantInfant-Italic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantInfant-Light.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantInfant-LightItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantInfant-Medium.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantInfant-MediumItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantInfant-Regular.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantInfant-SemiBold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantInfant-SemiBoldItalic.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantSC-Bold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantSC-Light.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantSC-Medium.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantSC-Regular.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantSC-SemiBold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantUnicase-Bold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantUnicase-Light.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantUnicase-Medium.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantUnicase-Regular.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantUnicase-SemiBold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantUpright-Bold.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantUpright-Light.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantUpright-Medium.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantUpright-Regular.ttf"
  font "Cormorant_Install_v#{version}/1. TrueType Font Files/CormorantUpright-SemiBold.ttf"

  # No zap stanza required
end
