cask "font-coelacanth" do
  version "0.1.0"
  sha256 "dc4efc80aa92eaf1987ae4fe26cd4e455b52eedf791386e12d739e0d31935250"

  url "https://gitlab.com/Fuzzypeg/coelacanth/-/raw/master/release/coelacanth_v#{version}.zip"
  name "Coelacanth"
  homepage "https://gitlab.com/Fuzzypeg/coelacanth"

  livecheck do
    url "https://gitlab.com/Fuzzypeg/coelacanth/-/releases/permalink/latest"
    strategy :header_match
  end

  font "Coelacanth.otf"
  font "CoelacanthBold.otf"
  font "CoelacanthBoldIt.otf"
  font "CoelacanthCaption.otf"
  font "CoelacanthCaptionBold.otf"
  font "CoelacanthCaptionBoldIt.otf"
  font "CoelacanthCaptionExtraLt.otf"
  font "CoelacanthCaptionExtraLtIt.otf"
  font "CoelacanthCaptionHeavy.otf"
  font "CoelacanthCaptionHeavyIt.otf"
  font "CoelacanthCaptionIt.otf"
  font "CoelacanthCaptionLt.otf"
  font "CoelacanthCaptionLtIt.otf"
  font "CoelacanthCaptionSemibd.otf"
  font "CoelacanthCaptionSemibdIt.otf"
  font "CoelacanthDisplay.otf"
  font "CoelacanthDisplayBold.otf"
  font "CoelacanthDisplayExtraLt.otf"
  font "CoelacanthDisplayHeavy.otf"
  font "CoelacanthDisplayLt.otf"
  font "CoelacanthDisplaySemibd.otf"
  font "CoelacanthExtraLt.otf"
  font "CoelacanthExtraLtIt.otf"
  font "CoelacanthHeavy.otf"
  font "CoelacanthHeavyIt.otf"
  font "CoelacanthIt.otf"
  font "CoelacanthLt.otf"
  font "CoelacanthLtIt.otf"
  font "CoelacanthPearl.otf"
  font "CoelacanthPearlBold.otf"
  font "CoelacanthPearlBoldIt.otf"
  font "CoelacanthPearlExtraLt.otf"
  font "CoelacanthPearlExtraLtIt.otf"
  font "CoelacanthPearlHeavy.otf"
  font "CoelacanthPearlHeavyIt.otf"
  font "CoelacanthPearlIt.otf"
  font "CoelacanthPearlLt.otf"
  font "CoelacanthPearlLtIt.otf"
  font "CoelacanthPearlSemibd.otf"
  font "CoelacanthPearlSemibdIt.otf"
  font "CoelacanthSemibd.otf"
  font "CoelacanthSemibdIt.otf"
  font "CoelacanthSubcapt.otf"
  font "CoelacanthSubcaptBold.otf"
  font "CoelacanthSubcaptBoldIt.otf"
  font "CoelacanthSubcaptExtraLt.otf"
  font "CoelacanthSubcaptExtraLtIt.otf"
  font "CoelacanthSubcaptHeavy.otf"
  font "CoelacanthSubcaptHeavyIt.otf"
  font "CoelacanthSubcaptIt.otf"
  font "CoelacanthSubcaptLt.otf"
  font "CoelacanthSubcaptLtIt.otf"
  font "CoelacanthSubcaptSemibd.otf"
  font "CoelacanthSubcaptSemibdIt.otf"
  font "CoelacanthSubhd.otf"
  font "CoelacanthSubhdBold.otf"
  font "CoelacanthSubhdExtraLt.otf"
  font "CoelacanthSubhdHeavy.otf"
  font "CoelacanthSubhdLt.otf"
  font "CoelacanthSubhdSemibd.otf"

  # No zap stanza required
end
