cask "font-geist-mono-nerd-font" do
  version "3.5.1"
  sha256 "d3ba4a7418cde16963fda0caa4f7ae866c509e0a864ec21e393455e1906e070c"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/GeistMono.tar.xz"
  name "GeistMono Nerd Font (Geist Mono)"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  livecheck do
    url :url
    strategy :github_latest
  end

  no_autobump! because: :bumped_by_upstream

  font "GeistMonoNerdFont-Black.otf"
  font "GeistMonoNerdFont-BlackItalic.otf"
  font "GeistMonoNerdFont-Bold.otf"
  font "GeistMonoNerdFont-BoldItalic.otf"
  font "GeistMonoNerdFont-ExtraBold.otf"
  font "GeistMonoNerdFont-ExtraBoldItalic.otf"
  font "GeistMonoNerdFont-ExtraLight.otf"
  font "GeistMonoNerdFont-ExtraLightItalic.otf"
  font "GeistMonoNerdFont-Italic.otf"
  font "GeistMonoNerdFont-Light.otf"
  font "GeistMonoNerdFont-LightItalic.otf"
  font "GeistMonoNerdFont-Medium.otf"
  font "GeistMonoNerdFont-MediumItalic.otf"
  font "GeistMonoNerdFont-Regular.otf"
  font "GeistMonoNerdFont-SemiBold.otf"
  font "GeistMonoNerdFont-SemiBoldItalic.otf"
  font "GeistMonoNerdFont-Thin.otf"
  font "GeistMonoNerdFont-ThinItalic.otf"
  font "GeistMonoNerdFontMono-Black.otf"
  font "GeistMonoNerdFontMono-BlackItalic.otf"
  font "GeistMonoNerdFontMono-Bold.otf"
  font "GeistMonoNerdFontMono-BoldItalic.otf"
  font "GeistMonoNerdFontMono-ExtraBold.otf"
  font "GeistMonoNerdFontMono-ExtraBoldItalic.otf"
  font "GeistMonoNerdFontMono-ExtraLight.otf"
  font "GeistMonoNerdFontMono-ExtraLightItalic.otf"
  font "GeistMonoNerdFontMono-Italic.otf"
  font "GeistMonoNerdFontMono-Light.otf"
  font "GeistMonoNerdFontMono-LightItalic.otf"
  font "GeistMonoNerdFontMono-Medium.otf"
  font "GeistMonoNerdFontMono-MediumItalic.otf"
  font "GeistMonoNerdFontMono-Regular.otf"
  font "GeistMonoNerdFontMono-SemiBold.otf"
  font "GeistMonoNerdFontMono-SemiBoldItalic.otf"
  font "GeistMonoNerdFontMono-Thin.otf"
  font "GeistMonoNerdFontMono-ThinItalic.otf"
  font "GeistMonoNerdFontPropo-Black.otf"
  font "GeistMonoNerdFontPropo-BlackItalic.otf"
  font "GeistMonoNerdFontPropo-Bold.otf"
  font "GeistMonoNerdFontPropo-BoldItalic.otf"
  font "GeistMonoNerdFontPropo-ExtraBold.otf"
  font "GeistMonoNerdFontPropo-ExtraBoldItalic.otf"
  font "GeistMonoNerdFontPropo-ExtraLight.otf"
  font "GeistMonoNerdFontPropo-ExtraLightItalic.otf"
  font "GeistMonoNerdFontPropo-Italic.otf"
  font "GeistMonoNerdFontPropo-Light.otf"
  font "GeistMonoNerdFontPropo-LightItalic.otf"
  font "GeistMonoNerdFontPropo-Medium.otf"
  font "GeistMonoNerdFontPropo-MediumItalic.otf"
  font "GeistMonoNerdFontPropo-Regular.otf"
  font "GeistMonoNerdFontPropo-SemiBold.otf"
  font "GeistMonoNerdFontPropo-SemiBoldItalic.otf"
  font "GeistMonoNerdFontPropo-Thin.otf"
  font "GeistMonoNerdFontPropo-ThinItalic.otf"

  # No zap stanza required
end
