# This file was generated by GoReleaser. DO NOT EDIT.
cask "wifitui" do
  name "wifitui"
  desc "Connect to known WiFi networks and store profiles, all from the terminal"
  homepage "https://github.com/tonur/wifitui"
  version "0.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wifitui"

  on_macos do
    on_intel do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-darwin-x86_64.tar.gz"
      sha256 "d363b11fdb64617b2e3bd45e043146e37e9d55e09804b391c576266dd6c8f63f"
    end
    on_arm do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-darwin-arm64.tar.gz"
      sha256 "6c7fd457f7fc3e55282afd1830ba339f357ba57185c9685c873bca2feba8b879"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-linux-x86_64.tar.gz"
      sha256 "be25717d0a55bfae25318f007449d7674f12084b558ad78f8aac898e5e7711c5"
    end
    on_arm do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-linux-arm64.tar.gz"
      sha256 "20161755ba58a1c38befeb3a181b72e17c47dd22f868bc152098925ba9bc454a"
    end
  end

  # No zap stanza required
end
