cask "font-redhat" do
  version "4.1.0"
  sha256 "c620b2b84df0f7bf8c176f74881b7614a835ed18189d28bb1a9945c74488e5b5"

  url "https://github.com/RedHatOfficial/RedHatFont/archive/refs/tags/#{version}.tar.gz"
  name "Red Hat"
  homepage "https://github.com/RedHatOfficial/RedHatFont/"

  font "RedHatFont-#{version}/fonts/Mono/otf/RedHatMono-Bold.otf"
  font "RedHatFont-#{version}/fonts/Mono/otf/RedHatMono-BoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Mono/otf/RedHatMono-Italic.otf"
  font "RedHatFont-#{version}/fonts/Mono/otf/RedHatMono-Light.otf"
  font "RedHatFont-#{version}/fonts/Mono/otf/RedHatMono-LightItalic.otf"
  font "RedHatFont-#{version}/fonts/Mono/otf/RedHatMono-Medium.otf"
  font "RedHatFont-#{version}/fonts/Mono/otf/RedHatMono-MediumItalic.otf"
  font "RedHatFont-#{version}/fonts/Mono/otf/RedHatMono-Regular.otf"
  font "RedHatFont-#{version}/fonts/Mono/otf/RedHatMono-SemiBold.otf"
  font "RedHatFont-#{version}/fonts/Mono/otf/RedHatMono-SemiBoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Black.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-BlackItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Bold.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-BoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-ExtraBold.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-ExtraBoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Italic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Light.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-LightItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Medium.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-MediumItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Regular.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-SemiBold.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-SemiBoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/variable/RedHatDisplayVF-Italic.ttf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/variable/RedHatDisplayVF.ttf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-Bold.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-BoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-Italic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-Light.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-LightItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-Medium.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-MediumItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-Regular.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-SemiBold.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-SemiBoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/variable/RedHatTextVF-Italic.ttf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/variable/RedHatTextVF.ttf"

  # No zap stanza required
end
