cask "font-recursive-desktop" do
  version "1.085"
  sha256 "cbcbdf7a0e181d284a9235e09ed5f3873e527bc5dd1d977df71cdc1ff937da02"

  url "https://github.com/arrowtype/recursive/releases/download/v#{version}/ArrowType-Recursive-#{version}.zip",
      verified: "github.com/arrowtype/recursive/"
  name "Recursive Desktop"
  homepage "https://www.recursive.design/"

  font "ArrowType-Recursive-#{version}/Recursive_Desktop/Recursive_VF_#{version}.ttf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-BdItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-Black.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-BlkItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-Bold.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-ExtraBd.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-Italic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-Light.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-LtItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-Med.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-MedItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-Regular.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-SemiBd.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-SmBdItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-XBdItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-XBlk.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoCslSt-XBlkItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-Black.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-BlackItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-Bold.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-BoldItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-ExBdItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-ExtraBold.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-Italic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-Light.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-LightItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-Med.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-MedItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-Regular.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-SemiBold.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-SmBdItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-XBlk.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveMonoLnrSt-XBlkItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-BdItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-Black.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-BlkItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-Bold.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-ExtraBd.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-Italic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-Light.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-LtItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-Med.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-MedItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-Regular.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-SemiBd.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-SmBdItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-XBdItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-XBlk.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansCslSt-XBlkItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-Black.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-BlackItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-Bold.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-BoldItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-ExBdItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-ExtraBold.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-Italic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-Light.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-LightItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-Med.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-MedItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-Regular.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-SemiBold.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-SmBdItalic.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-XBlk.otf"
  font "ArrowType-Recursive-#{version}/Recursive_Desktop/separate_statics/OTF/RecursiveSansLnrSt-XBlkItalic.otf"

  # No zap stanza required
end
