cask "font-redhat" do
  version "5.0.0"
  sha256 "10ab96fdc90b20aaa70b66006f7c0b52c75c7c71d543486ef9acc2697a55d341"

  url "https://github.com/RedHatOfficial/RedHatFont/archive/refs/tags/#{version}.tar.gz"
  name "Red Hat"
  homepage "https://github.com/RedHatOfficial/RedHatFont/"

  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/otf/RedHatMono-Bold.otf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/otf/RedHatMono-BoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/otf/RedHatMono-Italic.otf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/otf/RedHatMono-Light.otf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/otf/RedHatMono-LightItalic.otf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/otf/RedHatMono-Medium.otf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/otf/RedHatMono-MediumItalic.otf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/otf/RedHatMono-Regular.otf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/otf/RedHatMono-SemiBold.otf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/otf/RedHatMono-SemiBoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/variable/RedHatMono-Italic-VF.ttf"
  font "RedHatFont-#{version}/fonts/Mono/RedHatMono/variable/RedHatMono-VF.ttf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Black.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-BlackItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Bold.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-BoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-ExtraBold.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-ExtraBoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Italic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Light.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-LightItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Medium.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-MediumItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-Regular.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-SemiBold.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/otf/RedHatDisplay-SemiBoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/variable/RedHatDisplay-Italic-VF.ttf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatDisplay/variable/RedHatDisplay-VF.ttf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-Bold.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-BoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-Italic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-Light.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-LightItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-Medium.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-MediumItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-Regular.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-SemiBold.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/otf/RedHatText-SemiBoldItalic.otf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/variable/RedHatText-Italic-VF.ttf"
  font "RedHatFont-#{version}/fonts/Proportional/RedHatText/variable/RedHatText-VF.ttf"

  # No zap stanza required
end
