cask "font-victor-mono-nerd-font" do
  version "3.4.0"
  sha256 "9b4bd827fc59f60c5bd3306a31c148208522d5d6801b9fb5233c39c503013f2f"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/VictorMono.zip"
  name "VictorMono Nerd Font (Victor Mono)"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  livecheck do
    url :url
    strategy :github_latest
  end

  no_autobump! because: :bumped_by_upstream

  font "VictorMonoNerdFont-Bold.ttf"
  font "VictorMonoNerdFont-BoldItalic.ttf"
  font "VictorMonoNerdFont-BoldOblique.ttf"
  font "VictorMonoNerdFont-ExtraLight.ttf"
  font "VictorMonoNerdFont-ExtraLightItalic.ttf"
  font "VictorMonoNerdFont-ExtraLightOblique.ttf"
  font "VictorMonoNerdFont-Italic.ttf"
  font "VictorMonoNerdFont-Light.ttf"
  font "VictorMonoNerdFont-LightItalic.ttf"
  font "VictorMonoNerdFont-LightOblique.ttf"
  font "VictorMonoNerdFont-Medium.ttf"
  font "VictorMonoNerdFont-MediumItalic.ttf"
  font "VictorMonoNerdFont-MediumOblique.ttf"
  font "VictorMonoNerdFont-Oblique.ttf"
  font "VictorMonoNerdFont-Regular.ttf"
  font "VictorMonoNerdFont-SemiBold.ttf"
  font "VictorMonoNerdFont-SemiBoldItalic.ttf"
  font "VictorMonoNerdFont-SemiBoldOblique.ttf"
  font "VictorMonoNerdFont-Thin.ttf"
  font "VictorMonoNerdFont-ThinItalic.ttf"
  font "VictorMonoNerdFont-ThinOblique.ttf"
  font "VictorMonoNerdFontMono-Bold.ttf"
  font "VictorMonoNerdFontMono-BoldItalic.ttf"
  font "VictorMonoNerdFontMono-BoldOblique.ttf"
  font "VictorMonoNerdFontMono-ExtraLight.ttf"
  font "VictorMonoNerdFontMono-ExtraLightItalic.ttf"
  font "VictorMonoNerdFontMono-ExtraLightOblique.ttf"
  font "VictorMonoNerdFontMono-Italic.ttf"
  font "VictorMonoNerdFontMono-Light.ttf"
  font "VictorMonoNerdFontMono-LightItalic.ttf"
  font "VictorMonoNerdFontMono-LightOblique.ttf"
  font "VictorMonoNerdFontMono-Medium.ttf"
  font "VictorMonoNerdFontMono-MediumItalic.ttf"
  font "VictorMonoNerdFontMono-MediumOblique.ttf"
  font "VictorMonoNerdFontMono-Oblique.ttf"
  font "VictorMonoNerdFontMono-Regular.ttf"
  font "VictorMonoNerdFontMono-SemiBold.ttf"
  font "VictorMonoNerdFontMono-SemiBoldItalic.ttf"
  font "VictorMonoNerdFontMono-SemiBoldOblique.ttf"
  font "VictorMonoNerdFontMono-Thin.ttf"
  font "VictorMonoNerdFontMono-ThinItalic.ttf"
  font "VictorMonoNerdFontMono-ThinOblique.ttf"
  font "VictorMonoNerdFontPropo-Bold.ttf"
  font "VictorMonoNerdFontPropo-BoldItalic.ttf"
  font "VictorMonoNerdFontPropo-BoldOblique.ttf"
  font "VictorMonoNerdFontPropo-ExtraLight.ttf"
  font "VictorMonoNerdFontPropo-ExtraLightItalic.ttf"
  font "VictorMonoNerdFontPropo-ExtraLightOblique.ttf"
  font "VictorMonoNerdFontPropo-Italic.ttf"
  font "VictorMonoNerdFontPropo-Light.ttf"
  font "VictorMonoNerdFontPropo-LightItalic.ttf"
  font "VictorMonoNerdFontPropo-LightOblique.ttf"
  font "VictorMonoNerdFontPropo-Medium.ttf"
  font "VictorMonoNerdFontPropo-MediumItalic.ttf"
  font "VictorMonoNerdFontPropo-MediumOblique.ttf"
  font "VictorMonoNerdFontPropo-Oblique.ttf"
  font "VictorMonoNerdFontPropo-Regular.ttf"
  font "VictorMonoNerdFontPropo-SemiBold.ttf"
  font "VictorMonoNerdFontPropo-SemiBoldItalic.ttf"
  font "VictorMonoNerdFontPropo-SemiBoldOblique.ttf"
  font "VictorMonoNerdFontPropo-Thin.ttf"
  font "VictorMonoNerdFontPropo-ThinItalic.ttf"
  font "VictorMonoNerdFontPropo-ThinOblique.ttf"

  # No zap stanza required
end
