cask "font-hubot-sans" do
  version "1.0.1"
  sha256 "b460d36097a5c9a3e45710cbe1554589eaa5765d7c2c88df364516f3e27159b1"

  url "https://github.com/github/hubot-sans/releases/download/v#{version}/Hubot-Sans.zip"
  name "Hubot-Sans"
  homepage "https://github.com/github/hubot-sans"

  font "Hubot Sans/OTF/HubotSans-Black.otf"
  font "Hubot Sans/OTF/HubotSans-BlackItalic.otf"
  font "Hubot Sans/OTF/HubotSans-Bold.otf"
  font "Hubot Sans/OTF/HubotSans-BoldItalic.otf"
  font "Hubot Sans/OTF/HubotSans-ExtraBold.otf"
  font "Hubot Sans/OTF/HubotSans-ExtraBoldItalic.otf"
  font "Hubot Sans/OTF/HubotSans-ExtraLight.otf"
  font "Hubot Sans/OTF/HubotSans-ExtraLightItalic.otf"
  font "Hubot Sans/OTF/HubotSans-Italic.otf"
  font "Hubot Sans/OTF/HubotSans-Light.otf"
  font "Hubot Sans/OTF/HubotSans-LightItalic.otf"
  font "Hubot Sans/OTF/HubotSans-Medium.otf"
  font "Hubot Sans/OTF/HubotSans-MediumItalic.otf"
  font "Hubot Sans/OTF/HubotSans-Regular.otf"
  font "Hubot Sans/OTF/HubotSans-SemiBold.otf"
  font "Hubot Sans/OTF/HubotSans-SemiBoldItalic.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-Black.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-BlackItalic.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-Bold.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-BoldItalic.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-ExtraBold.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-ExtraBoldItalic.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-ExtraLight.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-ExtraLightItalic.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-Italic.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-Light.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-LightItalic.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-Medium.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-MediumItalic.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-Regular.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-SemiBold.otf"
  font "Hubot Sans/OTF/HubotSansCondensed-SemiBoldItalic.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-Black.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-BlackItalic.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-Bold.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-BoldItalic.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-ExtraBold.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-ExtraBoldItalic.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-ExtraLight.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-ExtraLightItalic.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-Italic.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-Light.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-LightItalic.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-Medium.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-MediumItalic.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-Regular.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-SemiBold.otf"
  font "Hubot Sans/OTF/HubotSansExpanded-SemiBoldItalic.otf"

  # No zap stanza required
end
