cask "font-inter" do
  version "4.0"
  sha256 "ff970a5d4561a04f102a7cb781adbd6ac4e9b6c460914c7a101f15acb7f7d1a4"

  url "https://github.com/rsms/inter/releases/download/v#{version}/Inter-#{version}.zip",
      verified: "github.com/rsms/inter/"
  name "Inter"
  homepage "https://rsms.me/inter/"

  font "InterVariable-Italic.ttf"
  font "InterVariable.ttf"
  font "extras/otf/Inter-Black.otf"
  font "extras/otf/Inter-BlackItalic.otf"
  font "extras/otf/Inter-Bold.otf"
  font "extras/otf/Inter-BoldItalic.otf"
  font "extras/otf/Inter-ExtraBold.otf"
  font "extras/otf/Inter-ExtraBoldItalic.otf"
  font "extras/otf/Inter-ExtraLight.otf"
  font "extras/otf/Inter-ExtraLightItalic.otf"
  font "extras/otf/Inter-Italic.otf"
  font "extras/otf/Inter-Light.otf"
  font "extras/otf/Inter-LightItalic.otf"
  font "extras/otf/Inter-Medium.otf"
  font "extras/otf/Inter-MediumItalic.otf"
  font "extras/otf/Inter-Regular.otf"
  font "extras/otf/Inter-SemiBold.otf"
  font "extras/otf/Inter-SemiBoldItalic.otf"
  font "extras/otf/Inter-Thin.otf"
  font "extras/otf/Inter-ThinItalic.otf"
  font "extras/otf/InterDisplay-Black.otf"
  font "extras/otf/InterDisplay-BlackItalic.otf"
  font "extras/otf/InterDisplay-Bold.otf"
  font "extras/otf/InterDisplay-BoldItalic.otf"
  font "extras/otf/InterDisplay-ExtraBold.otf"
  font "extras/otf/InterDisplay-ExtraBoldItalic.otf"
  font "extras/otf/InterDisplay-ExtraLight.otf"
  font "extras/otf/InterDisplay-ExtraLightItalic.otf"
  font "extras/otf/InterDisplay-Italic.otf"
  font "extras/otf/InterDisplay-Light.otf"
  font "extras/otf/InterDisplay-LightItalic.otf"
  font "extras/otf/InterDisplay-Medium.otf"
  font "extras/otf/InterDisplay-MediumItalic.otf"
  font "extras/otf/InterDisplay-Regular.otf"
  font "extras/otf/InterDisplay-SemiBold.otf"
  font "extras/otf/InterDisplay-SemiBoldItalic.otf"
  font "extras/otf/InterDisplay-Thin.otf"
  font "extras/otf/InterDisplay-ThinItalic.otf"

  # No zap stanza required
end
