name: Homebrew Cask Automerge
description: Merge cask version bump pull requests.
author: reitermarkus
branding:
  icon: git-pull-request
  color: yellow
inputs:
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
runs:
  using: docker
  image: Dockerfile
