cask "font-urw-core35" do
  version "1.0.0"
  sha256 "6cfedddd6733f99172778330b779d35e62360eebf6b7f36002ff65178ee21495"

  url "https://github.com/twardoch/urw-core35-fonts/archive/refs/tags/v#{version}.tar.gz"
  name "URW Core 35 Fonts"
  homepage "https://github.com/twardoch/urw-core35-fonts"

  conflicts_with cask: "font-urw-base35"

  font "urw-core35-fonts-#{version}/C059-BdIta.otf"
  font "urw-core35-fonts-#{version}/C059-Bold.otf"
  font "urw-core35-fonts-#{version}/C059-Italic.otf"
  font "urw-core35-fonts-#{version}/C059-Roman.otf"
  font "urw-core35-fonts-#{version}/D050000L.otf"
  font "urw-core35-fonts-#{version}/NimbusMonoPS-Bold.otf"
  font "urw-core35-fonts-#{version}/NimbusMonoPS-BoldItalic.otf"
  font "urw-core35-fonts-#{version}/NimbusMonoPS-Italic.otf"
  font "urw-core35-fonts-#{version}/NimbusMonoPS-Regular.otf"
  font "urw-core35-fonts-#{version}/NimbusRoman-Bold.otf"
  font "urw-core35-fonts-#{version}/NimbusRoman-BoldItalic.otf"
  font "urw-core35-fonts-#{version}/NimbusRoman-Italic.otf"
  font "urw-core35-fonts-#{version}/NimbusRoman-Regular.otf"
  font "urw-core35-fonts-#{version}/NimbusSans-Bold.otf"
  font "urw-core35-fonts-#{version}/NimbusSans-BoldItalic.otf"
  font "urw-core35-fonts-#{version}/NimbusSans-BoldOblique.otf"
  font "urw-core35-fonts-#{version}/NimbusSans-Italic.otf"
  font "urw-core35-fonts-#{version}/NimbusSans-Oblique.otf"
  font "urw-core35-fonts-#{version}/NimbusSans-Regular.otf"
  font "urw-core35-fonts-#{version}/NimbusSansNarrow-BdOblique.otf"
  font "urw-core35-fonts-#{version}/NimbusSansNarrow-Bold.otf"
  font "urw-core35-fonts-#{version}/NimbusSansNarrow-BoldOblique.otf"
  font "urw-core35-fonts-#{version}/NimbusSansNarrow-Oblique.otf"
  font "urw-core35-fonts-#{version}/NimbusSansNarrow-Regular.otf"
  font "urw-core35-fonts-#{version}/P052-Bold.otf"
  font "urw-core35-fonts-#{version}/P052-BoldItalic.otf"
  font "urw-core35-fonts-#{version}/P052-Italic.otf"
  font "urw-core35-fonts-#{version}/P052-Roman.otf"
  font "urw-core35-fonts-#{version}/StandardSymbolsPS.otf"
  font "urw-core35-fonts-#{version}/URWBookman-Demi.otf"
  font "urw-core35-fonts-#{version}/URWBookman-DemiItalic.otf"
  font "urw-core35-fonts-#{version}/URWBookman-Light.otf"
  font "urw-core35-fonts-#{version}/URWBookman-LightItalic.otf"
  font "urw-core35-fonts-#{version}/URWGothic-Book.otf"
  font "urw-core35-fonts-#{version}/URWGothic-BookOblique.otf"
  font "urw-core35-fonts-#{version}/URWGothic-Demi.otf"
  font "urw-core35-fonts-#{version}/URWGothic-DemiOblique.otf"
  font "urw-core35-fonts-#{version}/Z003-MediumItalic.otf"
  font "urw-core35-fonts-#{version}/C059-BdIta.ttf"
  font "urw-core35-fonts-#{version}/C059-Bold.ttf"
  font "urw-core35-fonts-#{version}/C059-Italic.ttf"
  font "urw-core35-fonts-#{version}/C059-Roman.ttf"
  font "urw-core35-fonts-#{version}/D050000L.ttf"
  font "urw-core35-fonts-#{version}/NimbusMonoPS-Bold.ttf"
  font "urw-core35-fonts-#{version}/NimbusMonoPS-BoldItalic.ttf"
  font "urw-core35-fonts-#{version}/NimbusMonoPS-Italic.ttf"
  font "urw-core35-fonts-#{version}/NimbusMonoPS-Regular.ttf"
  font "urw-core35-fonts-#{version}/NimbusRoman-Bold.ttf"
  font "urw-core35-fonts-#{version}/NimbusRoman-BoldItalic.ttf"
  font "urw-core35-fonts-#{version}/NimbusRoman-Italic.ttf"
  font "urw-core35-fonts-#{version}/NimbusRoman-Regular.ttf"
  font "urw-core35-fonts-#{version}/NimbusSans-Bold.ttf"
  font "urw-core35-fonts-#{version}/NimbusSans-BoldItalic.ttf"
  font "urw-core35-fonts-#{version}/NimbusSans-BoldOblique.ttf"
  font "urw-core35-fonts-#{version}/NimbusSans-Italic.ttf"
  font "urw-core35-fonts-#{version}/NimbusSans-Oblique.ttf"
  font "urw-core35-fonts-#{version}/NimbusSans-Regular.ttf"
  font "urw-core35-fonts-#{version}/NimbusSansNarrow-BdOblique.ttf"
  font "urw-core35-fonts-#{version}/NimbusSansNarrow-Bold.ttf"
  font "urw-core35-fonts-#{version}/NimbusSansNarrow-BoldOblique.ttf"
  font "urw-core35-fonts-#{version}/NimbusSansNarrow-Oblique.ttf"
  font "urw-core35-fonts-#{version}/NimbusSansNarrow-Regular.ttf"
  font "urw-core35-fonts-#{version}/P052-Bold.ttf"
  font "urw-core35-fonts-#{version}/P052-BoldItalic.ttf"
  font "urw-core35-fonts-#{version}/P052-Italic.ttf"
  font "urw-core35-fonts-#{version}/P052-Roman.ttf"
  font "urw-core35-fonts-#{version}/StandardSymbolsPS.ttf"
  font "urw-core35-fonts-#{version}/URWBookman-Demi.ttf"
  font "urw-core35-fonts-#{version}/URWBookman-DemiItalic.ttf"
  font "urw-core35-fonts-#{version}/URWBookman-Light.ttf"
  font "urw-core35-fonts-#{version}/URWBookman-LightItalic.ttf"
  font "urw-core35-fonts-#{version}/URWGothic-Book.ttf"
  font "urw-core35-fonts-#{version}/URWGothic-BookOblique.ttf"
  font "urw-core35-fonts-#{version}/URWGothic-Demi.ttf"
  font "urw-core35-fonts-#{version}/URWGothic-DemiOblique.ttf"
  font "urw-core35-fonts-#{version}/Z003-MediumItalic.ttf"

  # No zap stanza required
end
