name: Enable auto-merge for review

on:
  workflow_run:
    workflows:
      - Enable auto-merge
    types:
      - completed

permissions:
  actions: write

jobs:
  automerge-review:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request_review' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download `event.json` artifact
        id: download_event_json
        uses: actions/github-script@v6
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               ...context.repo,
               run_id: ${{ github.event.workflow_run.id }},
            })

            const eventArtifacts = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "event.json"
            })

            const download = await github.rest.actions.downloadArtifact({
               ...context.repo,
               artifact_id: eventArtifacts[0].id,
               archive_format: 'zip',
            })

            const fs = require('fs')
            fs.writeFileSync('${{ github.workspace }}/artifact.zip', Buffer.from(download.data))
      - name: Extract `event.json` and determine pull request and review info
        id: review_info
        run: |
          unzip artifact.zip

          echo "pull_request=$(jq -r .pull_request.number event.json)" >> "${GITHUB_OUTPUT}"
          echo "review=$(jq -r .review.id event.json)" >> "${GITHUB_OUTPUT}"
        if: steps.download_event_json.outcome == 'success'
      - name: Trigger workflow for review ${{ steps.review_info.outputs.review }} on pull request \#${{ steps.review_info.outputs.pull_request }}
        uses: benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385
        with:
          workflow: automerge
          inputs: >
            {
              "pull-request": "${{ steps.review_info.outputs.pull_request }}",
              "review": "${{ steps.review_info.outputs.review }}"
            }
        if: >
          steps.review_info.outputs.pull_request &&
          steps.review_info.outputs.review
