name: Dispatch Command

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  dispatch-command:
    if: startsWith(github.repository, 'Homebrew/')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch /rebase Command
        uses: peter-evans/slash-command-dispatch@f996d7b7aae9059759ac55e978cff76d91853301
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}
          reaction-token: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}
          commands: rebase
          permission: triage
          issue-type: pull-request
