name: Dispatch Command

on:
  issue_comment:
    types: [created]

jobs:
  dispatch-command:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch /rebase Command
        uses: peter-evans/slash-command-dispatch@7dd4ee1aa3be41c206a08dba4fa0c486cfd595ee
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          reaction-token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          commands: rebase
          permission: triage
          issue-type: pull-request
