name: Review

on: pull_request_target

jobs:
  review:
    if: startsWith(github.repository, 'Homebrew/')
    runs-on: ubuntu-latest
    steps:
      - name: Label Pull Request
        uses: Homebrew/actions/label-pull-requests@master
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          def: |
            [
              {
                "label": "documentation",
                "path": "(.*\\.md|\\.github/ISSUE_TEMPLATE/.*\\.yml)"
              }
            ]
        if: always()
