name: Self-approve a Pull Request

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        required: true

jobs:
  self-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Post Pull Request Review
        if: github.event.workflow_dispatch
        uses: Homebrew/actions/post-review@master
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          pull_request: ${{ github.event.inputs.pull_request }}
          event: APPROVE
          body: Self-approved by @${{ github.user }}.
